### ISSUE TITLE
Landing page showcase section is broken

### ISSUE THREAD

**Issue by larandersson** [vasttrafik/wso2-apim-developer-portal#1]
Seems like your latest commits broke the showcase section??

![screenshot from 2019-02-18 22-19-13](https://user-images.githubusercontent.com/8848818/52976875-7c66cb80-33cb-11e9-91e1-9b3686eb321a.png)

And the GTFS pages you committed are not reachable from the landing page

**Comment by christian-morin** [comment]
Fixed in release 2.2.10.
The GTFS-page was reachable from the menu, but added it as a footer as well.

Thank you!
